#!/usr/bin/env python3
"""
Phase 5 Advanced Retrieval Test
================================
Tests the full RAG pipeline with Phase 5 features:
1. Query Rewriting (HyDE / Multi-Query)
2. Advanced Retrieval (Vector / Hybrid)
3. Reranking (BGE / Cohere)
4. Citation Extraction

Usage:
    python test_orchestrator_flow.py

Prerequisites:
    1. PostgreSQL running.
    2. .env file configured with LLM and Embedding keys.
    3. (Optional) RERANKER_PROVIDER set to 'bge' or 'cohere'.
"""

import asyncio
import sys
import tempfile
from pathlib import Path

# ── path setup (src layout) ──────────────────────────────────────────────────
ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT / "src"))

from neat_rag.db.pool import pg_pool
from neat_rag.db.sessions import SessionRepository
from neat_rag.db.vector_store import get_vector_store
from neat_rag.agent.orchestrator import run_query
from neat_rag.ingestion.pipeline import IngestionPipeline
from neat_rag.config import settings

SAMPLE_TEXT = """
Neat-RAG Project Overview
Neat-RAG is a modern, agentic RAG system built with Pydantic AI and PostgreSQL.
It supports advanced retrieval techniques like HyDE and Multi-Query to improve recall.
The system uses a Cross-Encoder reranker to ensure the most relevant chunks are fed to the LLM.

Technical Stack
- Backend: FastAPI
- Database: PostgreSQL with pgvector
- LLM Orchestration: Pydantic AI
- Reranking: BGE-Reranker-v2-m3 or Cohere
- Embedding: OpenAI, Gemini, or Ollama

Citation System
Every answer generated by Neat-RAG includes citations in [n] format.
These citations link back to the exact document chunks used to generate the answer.
The backend extracts these markers and returns full source metadata to the frontend.
"""

def _section(title: str):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")

def _ok(msg: str): print(f"  \033[32m✓\033[0m {msg}")
def _info(msg: str): print(f"  \033[94mℹ\033[0m {msg}")

async def setup_test_data():
    _section("Step 1: Ingesting Test Data")
    
    # Write sample text to a temp file
    tmp = tempfile.NamedTemporaryFile(suffix=".txt", delete=False, mode="w", encoding="utf-8")
    tmp.write(SAMPLE_TEXT)
    tmp.close()
    tmp_path = Path(tmp.name)
    
    pipeline = IngestionPipeline(pg_pool=pg_pool)
    try:
        doc = await pipeline.run(tmp_path)
        _ok(f"Ingested test document: {doc.title} (ID: {doc.id})")
        return doc
    finally:
        tmp_path.unlink(missing_ok=True)

async def test_rag_pipeline(session_id: str):
    _section("Step 2: Testing RAG Pipeline (Phase 5)")
    
    questions = [
        "What are the advanced retrieval techniques supported by Neat-RAG?",
        "Tell me about the citation system.",
        "What is the technical stack of this project?"
    ]
    
    # Check current config
    _info(f"Rerank Enabled: {settings.ENABLE_RERANK}")
    _info(f"Reranker: {settings.RERANKER_PROVIDER} ({settings.RERANKER_MODEL})")
    _info(f"HyDE: {settings.ENABLE_HYDE}")
    _info(f"Multi-Query: {settings.ENABLE_MULTI_QUERY}")
    
    for q in questions:
        print(f"\n\033[95mQuestion:\033[0m {q}")
        print("\033[90m[Processing...]\033[0m")
        
        try:
            # Call the orchestrator (returns answer + citations)
            answer, citations = await run_query(question=q, session_id=session_id)
            
            print(f"\033[92mAnswer:\033[0m {answer}")
            
            if citations:
                print(f"\033[94mCitations ({len(citations)}):\033[0m")
                for c in citations:
                    print(f"  [{c.citation_number}] {c.document_title} - \"{c.content_snippet}...\"")
            else:
                print("\033[91mNo citations found in answer.\033[0m")
                
        except Exception as e:
            print(f"\033[91mError:\033[0m {e}")
            import traceback
            traceback.print_exc()

async def main():
    print(f"\nNeat-RAG Phase 5 Integration Test")

    await pg_pool.connect()
    vector_store = get_vector_store()
    await vector_store.connect()

    try:
        # 1. Setup Data
        doc = await setup_test_data()

        # 2. Setup Session
        async with pg_pool.get_connection() as conn:
            repo = SessionRepository(conn)
            session = await repo.create_session(title="Phase 5 Test Session")

        # 3. Run RAG Tests
        await test_rag_pipeline(session.id)

        # 4. Cleanup
        _section("Step 3: Cleanup")
        async with pg_pool.get_connection() as conn:
            await conn.execute("DELETE FROM documents WHERE id = $1::uuid", doc.id)
            await conn.execute("DELETE FROM sessions WHERE id = $1::uuid", session.id)
        _ok("Test data and session removed.")

    finally:
        await vector_store.disconnect()
        await pg_pool.disconnect()

if __name__ == "__main__":
    asyncio.run(main())
