"""Initial schema — all tables, HNSW vector index, pgvector extension.

Revision ID: 001
Revises: —
Create Date: 2026-05-14

Tables created:
  documents   — ingested document metadata
  chunks      — text chunks with pgvector embeddings (HNSW index)
  sessions    — chat sessions
  messages    — chat messages within a session
  ingest_jobs — async ingestion job tracking
  feedback    — thumbs-up/down per message
  api_keys    — hashed API keys for authentication

Design notes:
  - EMBEDDING_DIM is read from settings at migration time so you can switch
    embedding models by changing the env var and running a new migration.
  - The ivfflat index is replaced by HNSW (m=16, ef_construction=64) which
    gives better recall at all dataset sizes without requiring periodic VACUUM.
  - All primary keys are UUID generated by PostgreSQL (gen_random_uuid()).
  - Cascade deletes: document → chunks, session → messages.
"""
from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

from alembic import op

# Make Settings importable when running alembic from the project root.
sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "src"))
from neat_rag.config import settings  # noqa: E402

revision = "001"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = settings.EMBEDDING_DIM


def upgrade() -> None:
    # ── Prerequisites ────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ── documents ────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS documents (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            title       TEXT NOT NULL,
            source      TEXT NOT NULL,
            mime_type   TEXT NOT NULL DEFAULT 'application/octet-stream',
            metadata    JSONB NOT NULL DEFAULT '{}',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    # ── chunks ───────────────────────────────────────────────────────────────
    op.execute(dedent(f"""
        CREATE TABLE IF NOT EXISTS chunks (
            id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            document_id  UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            content      TEXT NOT NULL,
            embedding    vector({EMBEDDING_DIM}),
            start_char   INTEGER,
            end_char     INTEGER,
            metadata     JSONB NOT NULL DEFAULT '{{}}',
            created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    # HNSW index — better recall vs ivfflat, no periodic VACUUM needed.
    # m=16: number of bi-directional links per node.
    # ef_construction=64: search width during index build.
    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_chunks_embedding_hnsw
        ON chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """))

    # Full-text search index for hybrid retrieval
    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_chunks_content_fts
        ON chunks
        USING gin (to_tsvector('english', content))
    """))

    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_chunks_document_id ON chunks (document_id)"
    )

    # ── sessions ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS sessions (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id     TEXT,
            title       TEXT NOT NULL DEFAULT 'New Chat',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_sessions_user_id
        ON sessions (user_id)
        WHERE user_id IS NOT NULL
    """))

    # ── messages ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS messages (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            session_id  UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
            role        TEXT NOT NULL CHECK (role IN ('user', 'agent')),
            content     TEXT NOT NULL,
            metadata    JSONB NOT NULL DEFAULT '{}',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_messages_session_id
        ON messages (session_id, created_at)
    """))

    # ── ingest_jobs ───────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS ingest_jobs (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            filename    TEXT NOT NULL,
            status      TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
            progress    REAL NOT NULL DEFAULT 0.0
                            CHECK (progress >= 0.0 AND progress <= 1.0),
            error       TEXT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    # ── feedback ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS feedback (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            message_id  UUID NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            user_id     TEXT,
            rating      INTEGER NOT NULL CHECK (rating IN (1, -1)),
            comment     TEXT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (message_id, user_id)
        )
    """))

    # ── api_keys ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS api_keys (
            id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            hashed_key   TEXT NOT NULL UNIQUE,
            owner        TEXT NOT NULL,
            scopes       TEXT[] NOT NULL DEFAULT '{}',
            created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_used_at TIMESTAMPTZ
        )
    """))

    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_api_keys_hashed_key ON api_keys (hashed_key)"
    )


def downgrade() -> None:
    for table in ("api_keys", "feedback", "ingest_jobs", "messages", "sessions", "chunks", "documents"):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")

    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
