"""Initial schema — all tables, HNSW vector index, pgvector extension.

Revision ID: 001

Tables created:
  documents   — ingested document metadata
  chunks      — text chunks with pgvector embeddings (HNSW index)
  sessions    — chat sessions
  messages    — chat messages within a session
  ingest_jobs — async ingestion job tracking
  feedback    — thumbs-up/down per message
  api_keys    — hashed API keys for authentication

Design notes:
  - EMBEDDING_DIM is read from settings at migration time so you can switch
    embedding models by changing the env var and running a new migration.
  - The ivfflat index is replaced by HNSW (m=16, ef_construction=64) which
    gives better recall at all dataset sizes without requiring periodic VACUUM.
  - All primary keys are UUID generated by PostgreSQL (gen_random_uuid()).
  - Cascade deletes: document → chunks, session → messages.
"""
from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

from alembic import op

# Make Settings importable when running alembic from the project root.
sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "src"))
from neat_rag.config import settings  # noqa: E402

revision = "001"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = settings.EMBEDDING_DIM


def upgrade() -> None:
    # ── Prerequisites ────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ── documents ────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS documents (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            title       TEXT NOT NULL,
            source      TEXT NOT NULL,
            mime_type   TEXT NOT NULL DEFAULT 'application/octet-stream',
            metadata    JSONB NOT NULL DEFAULT '{}',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    # ── chunks ───────────────────────────────────────────────────────────────
    op.execute(dedent(f"""
        CREATE TABLE IF NOT EXISTS chunks (
            id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            document_id  UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            content      TEXT NOT NULL,
            embedding    vector({EMBEDDING_DIM}),
            start_char   INTEGER,
            end_char     INTEGER,
            metadata     JSONB NOT NULL DEFAULT '{{}}',
            created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    # HNSW index — better recall vs ivfflat, no periodic VACUUM needed.
    # m=16: number of bi-directional links per node.
    # ef_construction=64: search width during index build.
    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_chunks_embedding_hnsw
        ON chunks
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """))

    # Full-text search index for hybrid retrieval
    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_chunks_content_fts
        ON chunks
        USING gin (to_tsvector('english', content))
    """))

    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_chunks_document_id ON chunks (document_id)"
    )

    # ── sessions ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS sessions (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            user_id     TEXT,
            title       TEXT NOT NULL DEFAULT 'New Chat',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_sessions_user_id
        ON sessions (user_id)
        WHERE user_id IS NOT NULL
    """))

    # ── messages ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS messages (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            session_id  UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
            role        TEXT NOT NULL CHECK (role IN ('user', 'agent')),
            content     TEXT NOT NULL,
            metadata    JSONB NOT NULL DEFAULT '{}',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    op.execute(dedent("""
        CREATE INDEX IF NOT EXISTS idx_messages_session_id
        ON messages (session_id, created_at)
    """))

    # ── ingest_jobs ───────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS ingest_jobs (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            filename    TEXT NOT NULL,
            status      TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
            progress    REAL NOT NULL DEFAULT 0.0
                            CHECK (progress >= 0.0 AND progress <= 1.0),
            error       TEXT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """))

    # ── feedback ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS feedback (
            id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            message_id  UUID NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            user_id     TEXT,
            rating      INTEGER NOT NULL CHECK (rating IN (1, -1)),
            comment     TEXT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (message_id, user_id)
        )
    """))

    # ── api_keys ─────────────────────────────────────────────────────────────
    op.execute(dedent("""
        CREATE TABLE IF NOT EXISTS api_keys (
            id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            hashed_key   TEXT NOT NULL UNIQUE,
            owner        TEXT NOT NULL,
            scopes       TEXT[] NOT NULL DEFAULT '{}',
            created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_used_at TIMESTAMPTZ
        )
    """))

    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_api_keys_hashed_key ON api_keys (hashed_key)"
    )

    # ── Search Functions ─────────────────────────────────────────────────────
    
    # 1. match_chunks: Pure vector similarity search
    op.execute(dedent(f"""
        CREATE OR REPLACE FUNCTION match_chunks(
            query_embedding vector({EMBEDDING_DIM}),
            match_count INT DEFAULT 10
        )
        RETURNS TABLE (
            chunk_id UUID,
            document_id UUID,
            content TEXT,
            similarity FLOAT,
            metadata JSONB,
            document_title TEXT,
            document_source TEXT
        )
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RETURN QUERY
            SELECT 
                c.id AS chunk_id,
                c.document_id,
                c.content,
                (1 - (c.embedding <=> query_embedding))::double precision AS similarity,
                c.metadata,
                d.title AS document_title,
                d.source AS document_source
            FROM chunks c
            JOIN documents d ON c.document_id = d.id
            WHERE c.embedding IS NOT NULL
            ORDER BY c.embedding <=> query_embedding
            LIMIT match_count;
        END;
        $$;
    """))

    # 2. hybrid_search: Weighted combination of vector and keyword search
    op.execute(dedent(f"""
        CREATE OR REPLACE FUNCTION hybrid_search(
            query_embedding vector({EMBEDDING_DIM}),
            query_text TEXT,
            match_count INT DEFAULT 10,
            text_weight FLOAT DEFAULT 0.3
        )
        RETURNS TABLE (
            chunk_id UUID,
            document_id UUID,
            content TEXT,
            combined_score FLOAT,
            vector_similarity FLOAT,
            text_similarity FLOAT,
            metadata JSONB,
            document_title TEXT,
            document_source TEXT
        )
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RETURN QUERY
            WITH vector_results AS (
                SELECT 
                    c.id AS chunk_id,
                    c.document_id,
                    c.content,
                    (1 - (c.embedding <=> query_embedding))::double precision AS vector_sim,
                    c.metadata,
                    d.title AS doc_title,
                    d.source AS doc_source
                FROM chunks c
                JOIN documents d ON c.document_id = d.id
                WHERE c.embedding IS NOT NULL
            ),
            text_results AS (
                SELECT 
                    c.id AS chunk_id,
                    c.document_id,
                    c.content,
                    ts_rank_cd(to_tsvector('english', c.content), plainto_tsquery('english', query_text))::double precision AS text_sim,
                    c.metadata,
                    d.title AS doc_title,
                    d.source AS doc_source
                FROM chunks c
                JOIN documents d ON c.document_id = d.id
                WHERE to_tsvector('english', c.content) @@ plainto_tsquery('english', query_text)
            )
            SELECT 
                COALESCE(v.chunk_id, t.chunk_id) AS chunk_id,
                COALESCE(v.document_id, t.document_id) AS document_id,
                COALESCE(v.content, t.content) AS content,
                (
                    COALESCE(v.vector_sim, 0)::double precision * (1 - text_weight) +
                    COALESCE(t.text_sim, 0)::double precision * text_weight
                ) AS combined_score,
                COALESCE(v.vector_sim, 0)::double precision AS vector_similarity,
                COALESCE(t.text_sim, 0)::double precision AS text_similarity,
                COALESCE(v.metadata, t.metadata) AS metadata,
                COALESCE(v.doc_title, t.doc_title) AS document_title,
                COALESCE(v.doc_source, t.doc_source) AS document_source
            FROM vector_results v
            FULL OUTER JOIN text_results t ON v.chunk_id = t.chunk_id
            ORDER BY combined_score DESC
            LIMIT match_count;
        END;
        $$;
    """))


def downgrade() -> None:
    # Drop functions first
    op.execute("DROP FUNCTION IF EXISTS hybrid_search;")
    op.execute("DROP FUNCTION IF EXISTS match_chunks;")

    for table in ("api_keys", "feedback", "ingest_jobs", "messages", "sessions", "chunks", "documents"):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")

    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
